apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-api
spec:
  selector:
    matchLabels:
      app: mock-api
  template:
    metadata:
      labels:
        app: mock-api
    spec:
      containers:
        - name: mock-api
          image: mock-api
          imagePullPolicy: Never
