apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecowatt-twitter-bot
spec:
  selector:
    matchLabels:
      app: ecowatt-twitter-bot
  template:
    spec:
      containers:
        - name: ecowatt-twitter-bot
          env:
            - name: RTE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: RTE_CLIENT_ID
                  name: ecowatt-twitter-bot
            - name: RTE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: RTE_CLIENT_SECRET
                  name: ecowatt-twitter-bot
            - name: RTE_BASE_URL
              value: https://digital.iservices.rte-france.com
            - name: TWITTER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: TWITTER_CLIENT_ID
                  name: ecowatt-twitter-bot
            - name: TWITTER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: TWITTER_CLIENT_SECRET
                  name: ecowatt-twitter-bot
            - name: TWITTER_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TWITTER_TOKEN
                  name: ecowatt-twitter-bot
            - name: TWITTER_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  key: TWITTER_TOKEN_SECRET
                  name: ecowatt-twitter-bot
            - name: TWITTER_URL
              value: https://api.twitter.com/2/tweets
