apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecowatt-twitter-bot
spec:
  selector:
    matchLabels:
      app: ecowatt-twitter-bot
  template:
    metadata:
      labels:
        app: ecowatt-twitter-bot
    spec:
      containers:
        - name: ecowatt-twitter-bot
          image: ecowatt-twitter-bot
          volumeMounts:
            - name: tweet-template
              mountPath: /templates
      volumes:
        - name: tweet-template
          configMap:
            name: ecowatt-twitter-bot-template
