name: Continuous integration

on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ecowatt-twitter-bot

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Build Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: false
      #     tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:ci

  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [integration-test]

    if: ${{ github.event_name == 'push' || github.event_name == 'release' }}

    steps:
      - uses: actions/checkout@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build & Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
