name: Continuous integration

on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ecowatt-twitter-bot
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: europe-west1-b

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r cicd/requirements.txt

      - name: Build OCI
        run: python3 cicd/main.py build

      - name: Log in to registry
        if: ${{ github.event_name == 'release' || github.ref_name == 'main'}}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push OCI
        if: ${{ github.ref_name == 'main'}}
        env:
          IMAGE_REPOSITORY: ghcr.io/${{ github.repository_owner }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: python3 cicd/main.py build --push

      - name: Push OCI as release
        if: ${{ github.event_name == 'release' }}
        env:
          IMAGE_REPOSITORY: ghcr.io/${{ github.repository_owner }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: python3 cicd/main.py build --push

      - id: Authenticate to GCP
        if: ${{ github.event_name == 'release' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        if: ${{ github.event_name == 'release' }}
        uses: google-github-actions/setup-gcloud@v1

      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        if: ${{ github.event_name == 'release' }}
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

      - name: Deploy
        if: ${{ github.event_name == 'release' }}
        run: ls
